### ISSUE TITLE
[3] Really low priority, but dynamic template reloading without grunt so that we can avoid restarting the server each time we change a template.

### ISSUE THREAD

**Issue by dubwub** [austindoeswork/S2017-UPE-AI#10]
https://www.ericlagergren.com/blog/dynamic-template-reloading-go

**Comment by austindoeswork** [comment]
or we could just avoid templates altogether, and use regular html

**Comment by dubwub** [comment]
i think templates are the best way to avoid the copy pasting that would come from having a header and footer in every document

**Comment by dubwub** [comment]
Added TemplateWaiter to fix this exact issue. Unfortunately it's a little strange with emacs and their need to create .#backup files (aka interlocking), but there is a temporary workaround by editing .emacs.d/init.el (see README)
