### ISSUE TITLE
TODO: add fog of war

### ISSUE THREAD

**Issue by dubwub** [austindoeswork/S2017-UPE-AI#15]
Austin already added the p1/p2 routes, but I have yet to implement the Fog of War yet. This should be done in tandem with front-end showing dimmed fog of war.

**Comment by mattraneri** [comment]
Any updates on this?

**Comment by dubwub** [comment]
expect it sometime this week, gotta finish a few things for classes and then starting wednesday imtrucking through the todo list

**Comment by dubwub** [comment]
fog of war is up!
